[project]
name = "com-ishpdnya-uiaccess"
version = "1.0.0"
description = "UIACCESS 服务"
authors = [
    {name = "IsHPDuwu"},
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "class-widgets-sdk",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = []